# Generated by Django 3.2.7 on 2021-09-07 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invite', '0003_alter_invitation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invite_choices',
            new_name='invite_status',
        ),
        migrations.AddField(
            model_name='invitation',
            name='invite_to_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to=settings.AUTH_USER_MODEL),
        ),
    ]
