# Generated by Django 3.2.7 on 2021-09-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0004_auto_20210907_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invite_message',
            field=models.TextField(blank=True, max_length=225, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invite_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('sent', 'Sent')], max_length=10, null=True, verbose_name='Invite Status'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invite_to_email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invite_token',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Code'),
        ),
    ]
