# Generated by Django 3.2.7 on 2021-09-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_src',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='user uploaded avatar '),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='user default avatar'),
        ),
    ]
