# Generated by Django 3.2.7 on 2021-09-07 18:55

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_src',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.users.models.avatar_upload_dir, verbose_name='user uploaded avatar '),
        ),
    ]
